Step X must be finished before step Q can begin.
Step Y must be finished before step P can begin.
Step U must be finished before step F can begin.
Step V must be finished before step S can begin.
Step G must be finished before step R can begin.
Step T must be finished before step P can begin.
Step O must be finished before step D can begin.
Step R must be finished before step I can begin.
Step M must be finished before step F can begin.
Step L must be finished before step C can begin.
Step K must be finished before step H can begin.
Step D must be finished before step H can begin.
Step I must be finished before step W can begin.
Step S must be finished before step C can begin.
Step J must be finished before step Z can begin.
Step B must be finished before step A can begin.
Step A must be finished before step W can begin.
Step W must be finished before step F can begin.
Step P must be finished before step E can begin.
Step C must be finished before step Q can begin.
Step E must be finished before step Z can begin.
Step Q must be finished before step F can begin.
Step Z must be finished before step F can begin.
Step N must be finished before step H can begin.
Step H must be finished before step F can begin.
Step N must be finished before step F can begin.
Step K must be finished before step D can begin.
Step P must be finished before step F can begin.
Step Q must be finished before step Z can begin.
Step G must be finished before step W can begin.
Step E must be finished before step N can begin.
Step R must be finished before step Z can begin.
Step V must be finished before step R can begin.
Step Q must be finished before step N can begin.
Step U must be finished before step L can begin.
Step P must be finished before step N can begin.
Step S must be finished before step Q can begin.
Step G must be finished before step S can begin.
Step U must be finished before step E can begin.
Step M must be finished before step I can begin.
Step A must be finished before step N can begin.
Step W must be finished before step H can begin.
Step J must be finished before step A can begin.
Step M must be finished before step S can begin.
Step T must be finished before step I can begin.
Step E must be finished before step Q can begin.
Step C must be finished before step Z can begin.
Step B must be finished before step H can begin.
Step J must be finished before step F can begin.
Step G must be finished before step E can begin.
Step Q must be finished before step H can begin.
Step T must be finished before step B can begin.
Step V must be finished before step B can begin.
Step R must be finished before step F can begin.
Step V must be finished before step H can begin.
Step K must be finished before step N can begin.
Step A must be finished before step H can begin.
Step S must be finished before step E can begin.
Step I must be finished before step N can begin.
Step V must be finished before step I can begin.
Step M must be finished before step E can begin.
Step U must be finished before step G can begin.
Step J must be finished before step N can begin.
Step T must be finished before step K can begin.
Step D must be finished before step N can begin.
Step L must be finished before step S can begin.
Step P must be finished before step Z can begin.
Step X must be finished before step S can begin.
Step B must be finished before step W can begin.
Step R must be finished before step M can begin.
Step W must be finished before step Q can begin.
Step A must be finished before step Z can begin.
Step A must be finished before step F can begin.
Step G must be finished before step T can begin.
Step S must be finished before step A can begin.
Step J must be finished before step E can begin.
Step Y must be finished before step N can begin.
Step D must be finished before step J can begin.
Step D must be finished before step S can begin.
Step M must be finished before step W can begin.
Step U must be finished before step T can begin.
Step E must be finished before step H can begin.
Step S must be finished before step W can begin.
Step T must be finished before step C can begin.
Step A must be finished before step P can begin.
Step U must be finished before step V can begin.
Step U must be finished before step J can begin.
Step L must be finished before step B can begin.
Step L must be finished before step N can begin.
Step J must be finished before step C can begin.
Step L must be finished before step Q can begin.
Step K must be finished before step B can begin.
Step G must be finished before step H can begin.
Step W must be finished before step Z can begin.
Step C must be finished before step E can begin.
Step B must be finished before step Q can begin.
Step O must be finished before step Z can begin.
Step L must be finished before step J can begin.
Step R must be finished before step N can begin.
Step J must be finished before step P can begin.
Step Y must be finished before step F can begin.
