1:
	go run main1.go common.go game.go unit.go c.go <input

2:
	go run main2.go common.go game.go unit.go c.go <input

test:
	go test -v main1_test.go main1.go common.go game.go unit.go c.go
	go test -v main2_test.go main2.go common.go game.go unit.go c.go

